#!/bin/bash

mkdir -pv bin
echo "Building zoosearch..."
g++ -std=c++17 -Wall -Werror -o bin/zoosearch -I../src ../src/zoosearch.cpp || exit 1
echo "Running zoosearch unit tests..."
bin/zoosearch test || exit 1
echo "SUCCESS"
exit 0
