#!/bin/bash
rm -f output/*.txt
mkdir -pv bin
echo "Building zoosearch..."
g++ -std=c++17 -Wall -Werror -o bin/zoosearch -I../src \
    ../src/zoosearch.cpp \
    ../src/sapphire_calcparser.cpp \
    ../src/sapphire_prog_chaos.cpp \
    || exit 1
echo "Running zoosearch unit tests..."
bin/zoosearch test || exit 1
echo "Searching for attractors..."
bin/zoosearch search > output/search.txt || exit 1
diff {output,correct}/expressions.txt || exit 1
echo "SUCCESS"
exit 0
